name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
    paths:
      - "packages/webapp/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: lerna run build --scope=@listly/webapp

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LISTLY_ACB07 }}'
          channelId: live
          projectId: listly-acb07
